
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

############################################################################################### custom exec once starts here \\\

# exec-once = waybar
exec-once  = ~/.config/waybar/scripts/launch.sh
exec-once = swaync
exec-once = swww-daemon
exec-once = sleep 1 && swww restore
exec-once = sudo rm /var/lib/pacman/db.lck
# exec-once = fastfetch
