
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,1920x1080@60,auto,1
#monitor presets (3) can add more as u wish :)
# monitor=,1440x1080@60,auto,1
# monitor=,1280x1024@60,auto,1
# monitor=,1280x960@60,auto,1
# monitor=,transform,0
