##############################################################
##############################################################
##############################################################
###################### SOURCING FILES ########################
##############################################################
##############################################################
##############################################################

# monitors
source = ~/.config/hypr/modules/monitors.conf

# my programs // assigning programs -> terminal, file manager, menu
source = ~/.config/hypr/modules/programs.conf

# autostart processes
source = ~/.config/hypr/modules/autostart.conf

#enovironment variables
source = ~/.config/hypr/modules/env.conf

### LOOK AND FEEL ### ########## this i'll divide in 2 parts -> 1. decorations 2. animations (both conf file sources will be listed below!)

#decorations
source = ~/.config/hypr/modules/decorations.conf

#animations
source = ~/.config/hypr/modules/animations.conf

# windowrules + windows and workspaces
source = ~/.config/hypr/modules/windowrules.conf

# layouts
source = ~/.config/hypr/modules/layout.conf

#misc
source = ~/.config/hypr/modules/misc.conf

#input
source = ~/.config/hypr/modules/input.conf

#keybinds
source = ~/.config/hypr/modules/binds.conf

############################################## most people dont use permissions area but am still keeping it in in case u want to check it out.. :)
################### 
### PERMISSIONS ###
###################
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
